# Generated by Django 4.2.3 on 2023-07-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_content_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='order',
        ),
    ]
